### ISSUE TITLE
test imports wrong

### ISSUE THREAD

**Issue by ewindisch** [bcwaldon/python-gerrit#3]
> from gerrit import Client, ChangeDetails, Patch, AuthenticationError

You'll find that ChangeDetails and Patch are actually in gerrit.model.

from gerrit import Client, AuthenticaitonError
from gerrit.model import ChangeDetails, Patch

I haven't tested these changes as I do not currently have a /local/ Gerrit installation to test against.

Regards,
Eric Windisch

**Comment by bcwaldon** [comment]
Hey Eric, 

I'm glad to have you looking at this project! I've pushed it to the back burner for the past few months, but at some point I'm hoping to spend some cycles on it again.

As for this specific issue, you're 100% right.
